version: '2'

#networks:
#my-net:
networks:
  mymarket:
    external:
      name: my-net
#networks:
#mymarket:

services:

  ca.store2.mymarket.com:
    image: hyperledger/fabric-ca
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.store2.mymarket.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.store2.mymarket.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/75fa693f99b260007f826926376411490e6513543fe7cfd1f1d443c341f20421_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/store2.mymarket.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.store2.mymarket.com
    networks:
      - mymarket

  peer0.store2.mymarket.com:
    container_name: peer0.store2.mymarket.com
    image: hyperledger/fabric-peer
    environment:
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mymarket_mymarket
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=dev
      #- CORE_PEER_TLS_ENABLED=true
      # This disables mutual auth for gossip
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_ID=peer0.store2.mymarket.com
      - CORE_PEER_ADDRESS=peer0.store2.mymarket.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.store2.mymarket.com:7051
      #- CORE_PEER_GOSSIP_EXTERNALENDPOINT=172.21.112.177:7051
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LOCALMSPID=Store2MSP
      #- CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      #- CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - '7051:7051'
      - '7053:7053'
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/store2.mymarket.com/peers/peer0.store2.mymarket.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/store2.mymarket.com/peers/peer0.store2.mymarket.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    networks:
      - mymarket
    command: peer node start

  peer1.store2.mymarket.com:
    container_name: peer1.store2.mymarket.com
    image: hyperledger/fabric-peer
    environment:
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mymarket_mymarket
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=dev
      #- CORE_PEER_TLS_ENABLED=true
      # This disables mutual auth for gossip
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_ID=peer1.store2.mymarket.com
      - CORE_PEER_ADDRESS=peer1.store2.mymarket.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.store2.mymarket.com:7051
      #- CORE_PEER_GOSSIP_EXTERNALENDPOINT=172.21.112.177:17051
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_LOCALMSPID=Store2MSP
      #- CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      #- CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - '17051:7051'
      - '17053:7053'
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/store2.mymarket.com/peers/peer1.store2.mymarket.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/store2.mymarket.com/peers/peer1.store2.mymarket.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb2
    networks:
      - mymarket
    command: peer node start

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - mymarket

  cli2:
    container_name: cli2
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_DOCKER_HOSTCOFIG_NETWORKMODE=my-net
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.store2.mymarket.com:7051
      - CORE_PEER_LOCALMSPID=Store2MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/store2.mymarket.com/users/Admin@store2.mymarket.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash #-c "scripts/scripts.sh mymarketcc"
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - mymarket
